services:
  database:
    image: postgres:16
    container_name: datalakes_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./db/datalakes_schema.sql:/docker-entrypoint-initdb.d/datalakes_schema.sql
      - ./db/default_data.sql:/docker-entrypoint-initdb.d/default_data.sql